apiVersion: v1
kind: Configmap
metadata:
  name: pod-configmap
  labels:
    purpose: config
    env: dev
data: # Key-value pairs for configuration
  COURSE: "kubernetes"
  DURATION: "3 months"
  TRAINER: "SIVA KUMAR REDDY"

# ConfigMap is used to store configuration data in key-value pairs
# ConfigMap can be used to pass configuration data to pods and containers