apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: pod-configmap # Reference to the ConfigMap named pod-configmap

            # EnvFrom is used to load environment variables from a ConfigMap
            # Here we are loading all key-value pairs from the ConfigMap named pod-configmap